### PR TITLE
[ci] #4475: bump rust toolchain and dependencies

### LINKED ISSUE #4475: Bump Rust compiler version
We need to bump rust compiler version in the CI to the latest asap. It's blocking updating of dependencies

### PR DESCRIPTION
**Pull request by BAStos525**
### Description of the Change
Bump rust toolchain to `2024-04-18-nightly` in CI.

### Benefits

Close #4475

### CODE REVIEW

**Comment by mversic** [comment]
also update in `wasm_builder`

**Review by mversic — DISMISSED** [review]

**Review by mversic — APPROVED** [review]

**Review by mversic — APPROVED** [review]

**Review by mversic — APPROVED** [review]

**Comment by Erigara** [comment]
Lot's of warnings about `displaydoc::Display`

**Comment by mversic** [comment]
> A lot of warnings about `displaydoc::Display`

I'm aware, we'll fix those in time

**Comment by Erigara** [comment]
Error with no-default-features:
```
error: unused import: `iroha_primitives::time::TimeSource`
  --> /__w/iroha/iroha/data_model/src/transaction.rs:16:5
   |
16 | use iroha_primitives::time::TimeSource;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `-D unused-imports` implied by `-D unused`
   = help: to override `-D unused` add `#[allow(unused_imports)]`
```

**Review by mversic — APPROVED** [review]

**Review by mversic — DISMISSED** [review]

**Review by mversic — DISMISSED** [review]

**Review by mversic — DISMISSED** [review]

**Review by Erigara — APPROVED** [review]

**Review by mversic — APPROVED** [review]

**Pull request merged**
