### PR TITLE
Ansible install docker

### PR DESCRIPTION
**Pull request by x3medima17**
Added Ansible playbook that installs docker, adds user to the group and starts docker

### CODE REVIEW

**Comment by Warchant** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[deploy/ansible/setup.yml, line 4 at r1](https://reviewable.io:443/reviews/hyperledger/iroha/622#-KwA05HGrYt4AuyzaVah:-KwA05HGrYt4AuyzaVai:b-rhxc7r) ([raw file](https://github.com/hyperledger/iroha/blob/e8a5d340217d428dd892de6726284f14e02b4411/deploy/ansible/setup.yml#L4)):*
> ```YAML
> - hosts: all
>   vars:
>     user: dumitru #your user here
> ```

change user to `iroha`. Add better description what is this `user` about.

Also change name of the file to `provisioning.yml`.

---

*[deploy/ansible/setup.yml, line 7 at r1](https://reviewable.io:443/reviews/hyperledger/iroha/622#-KwA0a9CbFIRdLJZ0keR:-KwA0a9CbFIRdLJZ0keS:b-8ljmod) ([raw file](https://github.com/hyperledger/iroha/blob/e8a5d340217d428dd892de6726284f14e02b4411/deploy/ansible/setup.yml#L7)):*
> ```YAML
> 
>   tasks:
>     - name: Get docker script 
> ```

add commentaries, like
```
get_url:
   # 1. install docker 
```

---

*[deploy/ansible/setup.yml, line 14 at r1](https://reviewable.io:443/reviews/hyperledger/iroha/622#-KwA0llgIcFRmLrLKa5w:-KwA0llgIcFRmLrLKa5x:b-f2ijmt) ([raw file](https://github.com/hyperledger/iroha/blob/e8a5d340217d428dd892de6726284f14e02b4411/deploy/ansible/setup.yml#L14)):*
> ```YAML
>         validate_certs: false
> 
>     - name: Execute install script
> ```

```
# 2. Install docker
```

By  the way, if I execute this ansible playbook multiple times in a row, will it re-install docker every time?

---

*[deploy/ansible/setup.yml, line 19 at r1](https://reviewable.io:443/reviews/hyperledger/iroha/622#-KwA0xcfy_wYycOVH8AU:-KwA0xcgmvXiwOMGj44U:b-loa704) ([raw file](https://github.com/hyperledger/iroha/blob/e8a5d340217d428dd892de6726284f14e02b4411/deploy/ansible/setup.yml#L19)):*
> ```YAML
>         chdir: /tmp
> 
>     - name: add user mod
> ```

also add comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hyperledger/iroha/622)*

**Comment by Warchant** [comment]
Use `git commit -s -m "Message"` (-s) to sign DCO.

**Comment by Warchant** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hyperledger/iroha/622)*

**Comment by x3medima17** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[deploy/ansible/provisioning.yml, line 4 at r1](https://reviewable.io:443/reviews/hyperledger/iroha/622#-KwA05HGrYt4AuyzaVah:-KwEYdmWvcfPgArx7NX-:b-896fix) ([raw file](https://github.com/hyperledger/iroha/blob/e8a5d340217d428dd892de6726284f14e02b4411/deploy/ansible/provisioning.yml#L4)):*
<details><summary><i>Previously, Warchant (Bogdan) wrote…</i></summary><blockquote>

change user to `iroha`. Add better description what is this `user` about.

Also change name of the file to `provisioning.yml`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hyperledger/iroha/622)*

**Comment by x3medima17** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[deploy/ansible/provisioning.yml, line 7 at r1](https://reviewable.io:443/reviews/hyperledger/iroha/622#-KwA0a9CbFIRdLJZ0keR:-KwEZ9OT4nyIplQnizoc:b-896fix) ([raw file](https://github.com/hyperledger/iroha/blob/e8a5d340217d428dd892de6726284f14e02b4411/deploy/ansible/provisioning.yml#L7)):*
<details><summary><i>Previously, Warchant (Bogdan) wrote…</i></summary><blockquote>

add commentaries, like
```
get_url:
   # 1. install docker 
```
</blockquote></details>

Done.

---

*[deploy/ansible/provisioning.yml, line 14 at r1](https://reviewable.io:443/reviews/hyperledger/iroha/622#-KwA0llgIcFRmLrLKa5w:-KwEZAKQ1V8um7tpoKjh:bx1euo) ([raw file](https://github.com/hyperledger/iroha/blob/e8a5d340217d428dd892de6726284f14e02b4411/deploy/ansible/provisioning.yml#L14)):*
<details><summary><i>Previously, Warchant (Bogdan) wrote…</i></summary><blockquote>

```
# 2. Install docker
```

By  the way, if I execute this ansible playbook multiple times in a row, will it re-install docker every time?
</blockquote></details>

If docker is installed, it will not install it again

---

*[deploy/ansible/provisioning.yml, line 19 at r1](https://reviewable.io:443/reviews/hyperledger/iroha/622#-KwA0xcfy_wYycOVH8AU:-KwEZJovi3bDC4CeZ9EB:b-896fix) ([raw file](https://github.com/hyperledger/iroha/blob/e8a5d340217d428dd892de6726284f14e02b4411/deploy/ansible/provisioning.yml#L19)):*
<details><summary><i>Previously, Warchant (Bogdan) wrote…</i></summary><blockquote>

also add comment
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hyperledger/iroha/622)*

**Comment by Warchant** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hyperledger/iroha/622#-:-KwEddCrHR0AGGWlqRQG:bnfp4nl)*

**Pull request merged**
