### PR TITLE
Fixing warning in command SubtractAssetQuantity, removing unnecessarily includes, small documentation change

### PR DESCRIPTION
**Pull request by baziorek**
## Description
After successful merges:  https://github.com/hyperledger/iroha/pull/4003 and https://github.com/hyperledger/iroha/pull/4032 I was compiling entire Iroha 1.

1. I've noticed some warning, which may cause that the command is not working properly.
2. I've also corrected warnings connected with unused includes.
3. I remember that many times I was asking @6r1d how to merge approved Pull Request, he suggested that this information should be in CONTRIBUTION.rst - so I've added its.

### Linked issue

Closes #{issue_number} 

### Benefits
1. Fix of undetected bug
2. Faster compilation time and less warnings from IDE
3. No more questions to @6r1d about what button to press:)

### Checklist

- [x] I've read `CONTRIBUTING.md` - I even edited the file:D
- [x] I've used the standard signed-off commit format (or will squash just before merging)
- [ ] All applicable CI checks pass (or I promised to make them pass later) - we will see
- [ ] (optional) I've written unit tests for the code changes - not required
- [ ] I replied to all comments after code review, marking all implemented changes with thumbs up

### CODE REVIEW

**Review by 6r1d — APPROVED** [review]
If tests pass, LGTM. Thanks for the doc update.

**Comment by baziorek** [comment]
It looks that something is wrong with Golang dependencies:
image
I'll try to add suggested command in Dockerfile and we will see if it helped.

**Comment by baziorek** [comment]
> It looks that something is wrong with Golang dependencies: image I'll try to add suggested command in Dockerfile and we will see if it helped.

It looks that after changes in Dockerfile in commit https://github.com/hyperledger/iroha/pull/4251/commits/cb8be6480693a3c8baf965b099ab03e1b348aa27 - everything works.

**Comment by baziorek** [comment]
@6r1d Your approve disappeared after my last comment, could You please take a look again?

**Review by 6r1d — DISMISSED** [review]

**Review by 6r1d — APPROVED** [review]

**Comment by baziorek** [comment]
Thanks for approve @6r1d . It is crazy situation. Everything was ready for merge: green approved and up-to-date widh destination branch. But suddenly I needed to press "Update branch" - it caused that again there are problems with docker. I have one friend who knows golang - hopefully he will help me to fix this:D.

I tried to add in Dockerfile:

- `RUN go mod download github.com/golang/protobuf`
- `RUN go mod tidy # according to: https://stackoverflow.com/questions/67203641/missing-go-sum-entry-for-module-providing-package-package-name`
- `RUN go mod tidy -e # according to: https://stackoverflow.com/questions/67203641/missing-go-sum-entry-for-module-providing-package-package-name`
- `RUN go mod init # according to: https://golangdocs.com/create-go-modules`
- `RUN go mod init $(go env GOPATH) # according to: https://golangdocs.com/create-go-modules`
- `RUN go install github.com/golang/protobuf/protoc-gen-go`
- `RUN go install github.com/golang/protobuf/protoc-gen-go@latest'`

without success :(

**Review by 6r1d — APPROVED** [review]

**Comment by baziorek** [comment]
It is green and approved by @6r1d and corrected by @SamHSmith so I'm merging:).

**Pull request merged**
