### PR TITLE
Feature/impl-torii-stub

### PR DESCRIPTION
**Pull request by MizukiSonoko**
## What is this pull request?
Implements torii stub  IR-158
   
## Why do you implement it? Why do we need this pull request?
- All client developer can develop an application using Torii stub.
  
## How to use the features provided in the pull request?
- Todo 

## Details/Features
- [ ] change directory structure
- [ ] Implements torii/service.cpp

### change directory structure   
```
├─ torii/
│   └─ service.cpp/hpp
│      └─ processor/ 
│         ├─ client_processor.cpp/hpp
│         └─ transaction_processor.cpp/hpp
├─ processor/ 
│   └─ query_processor.cpp/hpp (pending/I think query is not in torii)
```

#### torii/service.cpp
It contains `class CommandService final : public iroha::protocol::CommandService::Service{}`

#### processor/transaction_processor.hpp/cpp
It contains 
- invoke stateless validation
- send tx to ordering service

## P.S.
- I want to make best structure about
    - network/
    - torii/
    - processor/

### CODE REVIEW

**Comment by muratovv** [comment]
@MizukiSonoko 
>I want to make best structure about
>* network/
>* torii/
>* processor/

As i correct understand "network" folder is about peer-to-peer communication, "torii" is only about server, and "processor" is about interaction with client?

**Comment by MizukiSonoko** [comment]
I think "network" folder is a little fat,
but other is correct.
"torii" is only about server(grpc + protobuf + dao),
"processor" is about interaction with client ( invoke stateless, sent tx to ordering service...)

**Comment by muratovv** [comment]
In terms of irohad "processor" folder looks very confusing, isn't it? I suppose that processor is a part of peer-client interaction.

**Comment by MizukiSonoko** [comment]
> In terms of irohad "processor" folder looks very confusing, isn't it?
I think so

> I suppose that processor is a part of peer-client interaction.
What's peer-client interaction? 
It's like Torii(Interface) or ClientProcessor(Implemets)?

**Comment by muratovv** [comment]
>What's peer-client interaction?

All stuff that related to receive intents from user (queries and transactions) and provide response (notify from command/tx processors).

>It's like Torii(Interface) or ClientProcessor(Implemets)?

I suppose torii get this interface as own dependency. Like this:
`auto torii = Torii(ClientProcessor &processor)`

**Comment by MizukiSonoko** [comment]
Ok, I understand it...
And I will change processor folder name before merging this pull req.

**Comment by muratovv** [comment]
May we should stay processors inside torii folder?  This will be more convenient with other modules and current understanding of irohad architecture.

**Comment by MizukiSonoko** [comment]
If some processors is not used by other module. It's ok but
If other module uses some processors, we should separate processors from torii.

**Comment by muratovv** [comment]
Processors currently use only in torii

**Comment by MizukiSonoko** [comment]
ok I will keep it

**Pull request merged**
