### PR TITLE
Feature/transaction builder

### PR DESCRIPTION
**Pull request by motxx**
- Transaction Builder
- How to:

```cpp
#include "model/transaction_builder/transaction_builder.hpp"

using transaction::TransactionBuilder;
using type_signatures::Add;

auto txDomain = TransactionBuilder<Add<object::Domain>>()
  .setSender("karin")
  .setDomain(object::Domain({"pubkey1", "pubkey2"}, "name"))
  .build();
```

### CODE REVIEW

**Comment by motxx** [comment]
This PR is for `feature/use-flatbuffer`. Currently we are using gRPC, so I temporarily close this PR.

**Comment by Warchant** [comment]
Do not delete this branch, it will be reopened later. @motxx

**Comment by motxx** [comment]
Sorry for my mistake.

**Comment by motxx** [comment]
This branch is obsolete. Some unmerged commits exist, but we don't use them. So I'll delete this branch.

**Pull request closed without merging**
