### PR TITLE
Docs: query ordering

### PR DESCRIPTION
**Pull request by MBoldyrev**
Signed-off-by: Mikhail Boldyrev <miboldyrev@gmail.com>

### Description of the Change

documentation for #338

### CODE REVIEW

**Comment by LiraLemur** [comment]
@MBoldyrev I tried something here. What do you think of the idea? I still think there should be a little more info on where to add the pagination stuff but what it looks like n general?

**Comment by MBoldyrev** [comment]
@LiraLemur thank you, the PR seems ready

**Comment by LiraLemur** [comment]
@mboldyrev You think so? I am not sure it's easy to understand  how to add pagination to the queries though. Maybe let's ask someone like a QA person to take a quick look? I mean I'm not very techy and so maybe it is something obvious. But what if it's not? 
God, I miss 2 review rule :D

**Comment by MBoldyrev** [comment]
summon @stepanlavrentev

**Pull request merged**
