### PR TITLE
[refactor] #2675: Validate item names/ids without allocating Vec

### PR DESCRIPTION
**Pull request by suiwenfeng**
Signed-off-by: Wenfeng Sui suiwenfeng@qq.com

### CODE REVIEW

**Review by Erigara — DISMISSED** [review]
LGTM

**Review by ilchu — DISMISSED** [review]
Nice and sleek. I failed to avoid vector allocation myself when writing proxy logic, so this contribution is much appreciated.

**Comment by suiwenfeng** [comment]
@ilchu @Erigara Please help approve by done review again. 

the pr not passed the DCO check before.

**Review by Erigara — APPROVED** [review]

**Review by ilchu — APPROVED** [review]

**Comment by suiwenfeng** [comment]
@Erigara Looks this codecov check not work, because it compared to an earlier commit, and blocked this pr, can you help bypaas it?

**Pull request merged**
