### PR TITLE
Refactor logger format

### PR DESCRIPTION
**Pull request by grimadas**
### Description of the Change

Add date to logger and refactor the format

### Benefits

Now we have full date in logger

### Possible Drawbacks 
Check the new format: 
Non debug mode
image
Debug mode:
image

### CODE REVIEW

**Comment by l4l** [comment]
Would be nice to:
1. Separate date&thread info, e.g in `[` `]` brackets as it was before
2. Make it configurable, e.g thread info can be useless sometime (moreover it's useful for debuging i tihnk)

**Comment by luckychess** [comment]
Could you also please print thread ids in hex format? It would be a way more comfortable to read.

**Comment by bakhtin** [comment]
LGTM from log processing point of view. Please, fix as suggested to make it more readable.

**Comment by neewy** [comment]
can we also please add milliseconds to track time more precisely?

**Pull request merged**
