### PR TITLE
Switch from java-8-oracle to java-9-openjdk

### PR DESCRIPTION
**Pull request by bakhtin**
Signed-off-by: Artyom Bakhtin <a@bakhtin.net>

### Description of the Change
Switch Java version in develop Dockerfile from Oracle Java 8 to OpenJDK 9. Previous version is no more available by the URL (returns 404)

### Benefits
develop Dockerfile build in now passing successfully

### Possible Drawbacks 
A small chance that bindings generated with Oracle Java can be incompatible with OpenJDK

### CODE REVIEW

**Comment by bakhtin** [comment]
Do you use bindings generated with Java from that image? Or use this image directly?

**Comment by bakhtin** [comment]
As long as Java update would not break anything for SORA team, I'll keep this version bump. Having the most recent version of the software is always a good practice.

**Comment by neewy** [comment]
@bakhtin did you check that bindings, generated with this version, actually work?

**Comment by bakhtin** [comment]
I checked it can be compiled. Although, not use them to interact with Iroha instance

**Comment by bakhtin** [comment]
`ppa:webupd8team/java` is now live (it was down for some time) again. And Java 9 has reached EOL. As Java 8 is LTS we'll stick to this version for now. I'm closing this PR

**Pull request closed without merging**
