### PR TITLE
 [refactor] #3874: Removes `IsAssetDefinitionOwnerQuery`

### PR DESCRIPTION
**Pull request by benhhack**
## Description

Removed all instances of `IsAssetDefinitionOwner` except for some:

**In `wasm/validator/src/permission.rs` and `/default.rs**

With the function

```rust
fn is_asset_definition_owner(
        asset_definition_id: &AssetDefinitionId,
        authority: &AccountId,
    ) -> Result<bool> {
        IsAssetDefinitionOwner::new(asset_definition_id.clone(), authority.clone()).execute()
    }
```

I am unsure what to replace this result with. I have tried replacing it with `FindAssetDefinitionById` (since this is said to do the exact same thing as is asset definition owner in #3874) but this creates build errors. Should I delete everything that uses the `is_asset_definition_owner` function as well?

### Linked issue

Remove `IsAssetDefinitionOwnerQuery`

This query was introduced only for the purposes of validator. Since #3442 we can use `FindAssetDefinitionById` to do the exact same thing.

Closes #3442

### Checklist

- [x] I've read `CONTRIBUTING.md`
- [ ] I've used the standard signed-off commit format (or will squash just before merging)
- [ ] All applicable CI checks pass (or I promised to make them pass later)
- [ ] (optional) I've written unit tests for the code changes
- [ ] I replied to all comments after code review, marking all implemented changes with thumbs up

### CODE REVIEW

**Comment by 6r1d** [comment]
Hello, Ben.
I will notify the others about this commit, but in the meantime, could you please sign-off your commit with `git commit --amend --signoff` and force-push to your branch?
Thanks.

**Comment by mversic** [comment]
> Should I delete everything that uses the is_asset_definition_owner function as well?

no

> I am unsure what to replace this result with. I have tried replacing it with `FindAssetDefinitionById`

you execute `FindAssetDefinitionById` query to get `AssetDefinition` and then compare `AssetDefinition::Owner` with `authority`

**Comment by mversic** [comment]
1. you are missing signoff again
2. you need to run `cargo run --bin kagami -- schema > docs/source/references/schema.json` and push the changes

**Comment by benhhack** [comment]
Thanks for the help. I'm getting problems with the `mod` tests and unfortunately, I don't know enough about Rust or the system to try to fix them. I'm doing research but also thought maybe you could help. The error response is  

```
fatal runtime error: failed to initiate panic, error 5
error: test failed, to rerun pass `-p iroha_client --test mod`

Caused by:
  process didn't exit successfully: `<my-path>/iroha/target/debug/deps/mod-215035c2a4074a62 --nocapture` (signal: 6, SIGABRT: process abort signal)
```

The error looks like its coming from snapshot creation, when I run the tests more verbosely the line

`2023-09-26T12:56:30.185430Z ERROR iroha_core::snapshot: Failed to create snapshot for wsv. error=Failed reading/writing "./storage/snapshot.tmp" from disk` shows up. 

Please advise on next steps.

Let me know how to provide any other information that may be helpful.

**Comment by mversic** [comment]
> Please advise on next steps.

run `cargo test` locally

**Comment by benhhack** [comment]
> run `cargo test` locally

Yes I have run this locally and I receive the error above with the tests in `client`.

**Comment by mversic** [comment]
> Yes I have run this locally and I receive the error above with the tests in client.

oh, you also have to run: `cargo run --release --bin kagami -- validator > configs/peer/validator.wasm` and push the changes

**Comment by benhhack** [comment]
> cargo run --release --bin kagami -- validator > configs/peer/validator.wasm

Okay, will do. Is this in the developer docs somewhere?

**Comment by benhhack** [comment]
> > Yes I have run this locally and I receive the error above with the tests in client.
> 
> oh, you also have to run: `cargo run --release --bin kagami -- validator > configs/peer/validator.wasm` and push the changes

I have done this and am getting the following error 

```bash
    Finished release [optimized] target(s) in 3m 08s
     Running `target/release/kagami validator`
error: unrecognized subcommand 'validator'
```

Is there any documentation I can look at for kagami/these commands? What is their purpose?

**Comment by mversic** [comment]
> Is there any documentation I can look at for kagami/these commands? What is their purpose?

sorry, I forgot we changed API for this recently. This command rebuilds `validator`/`executor` smartcontract:
`cargo run --bin iroha_wasm_builder_cli build --optimize --outfile configs/peer/validator.wasm default_validator`

**Comment by mversic** [comment]
@benhhack I hope you will fix CI errors so we can merge this

**Comment by benhhack** [comment]
> @benhhack I hope you will fix CI errors so we can merge this

Yes, am working my way through trying to figure out commit squashing/message amending since its not something I've done before.

**Comment by mversic** [comment]
@benhhack you still have a conflict to resolve :)

**Comment by mversic** [comment]
@benhhack hi, can we expect an update this week?

**Comment by benhhack** [comment]
> @benhhack hi, can we expect an update this week?

Hi yes, will be working on this tomorrow

**Comment by benhhack** [comment]
Hi @mversic. I'm unsure how to solve this conflict since I can't view the wasm file. Do you have any tips? I'd love to learn more about what's going on to pointing to any resources would also be very helpful. 

I should also point out that not all the tests are passing despite running the commands you mentioned. Do you have any ideas?

**Comment by mversic** [comment]
> Hi @mversic. I'm unsure how to solve this conflict since I can't view the wasm file. Do you have any tips? I'd love to learn more about what's going on to pointing to any resources would also be very helpful.
> 
> I should also point out that not all the tests are passing despite running the commands you mentioned. Do you have any ideas?

yes, you cannot see contents of a binary file. You have to build new `validator.wasm` with the command I have given previously and replace current validator with that one. That will resolve conflicts

**Comment by benhhack** [comment]
> > Hi @mversic. I'm unsure how to solve this conflict since I can't view the wasm file. Do you have any tips? I'd love to learn more about what's going on to pointing to any resources would also be very helpful.
> > I should also point out that not all the tests are passing despite running the commands you mentioned. Do you have any ideas?
> 
> yes, you cannot see contents of a binary file. You have to build new `validator.wasm` with the command I have given previously and replace current validator with that one. That will resolve conflicts

I have just done that and I see that the conflicts are not resolved.

**Comment by mversic** [comment]
> I have just done that and I see that the conflicts are not resolved.

have you fetched latest changes from iroha2-dev and rebased your PR? First do that, then rebuild `validator.wasm`

**Comment by benhhack** [comment]
> > I have just done that and I see that the conflicts are not resolved.
> 
> have you fetched latest changes from iroha2-dev and rebased your PR? First do that, then rebuild `validator.wasm`

Yeah I have but will try that again.

**Comment by mversic** [comment]
> > > I have just done that and I see that the conflicts are not resolved.
> > 
> > 
> > have you fetched latest changes from iroha2-dev and rebased your PR? First do that, then rebuild `validator.wasm`
> 
> Yeah I have but will try that again.

you have not rebased to latest iroha2-dev. Check what is latest commit (that is not yours) on your branch and what is latest commit on iroha2-dev. You will see additional commits on iroha2-dev branch

**Comment by benhhack** [comment]
The DCO check is now failing because some of the commits I've rebased on top of seem not to have signoffs.

**Comment by mversic** [comment]
> The DCO check is now failing because some of the commits I've rebased on top of seem not to have signoffs.

DCO is the least of your concerns. Somehow you have made a mess of your local git history. Github now shows that you have modified 99 files. You will have to fix this

**Comment by benhhack** [comment]
How is it looking now @mversic ?

**Comment by mversic** [comment]
@benhhack please fix failing CI jobs, all tests are passing but you have formatting issues

**Comment by benhhack** [comment]
> @benhhack please fix failing CI jobs, all tests are passing but you have formatting issues

Apologies, have run nightly and pushed the changes.

**Comment by mversic** [comment]
@benhhack please squash your commits into 1 and I will approve your PR

**Comment by benhhack** [comment]
I'm struggling with the squashing because of the validator.wasm merge conflicts. A standard interactive rebase isn't working. Do you have any tips?

**Comment by mversic** [comment]
> @mversic I'm struggling with the squashing because of the validator.wasm merge conflicts. A standard interactive rebase isn't working. Do you have any tips?

you can have a look [here](https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together). Tell me if this helps, we would like to merge this PR soon

**Comment by benhhack** [comment]
@mversic all the updates have definitely confused things, one of the recent ones also seems to have overlapping work with this one here. Again apologies for taking so long with this. I appreciate the assistance and I'm learning a lot. I'm going to refork the repository in its most updated form and work from there so that I can have a clean commit history without all the merging.

**Pull request closed without merging**
