### PR TITLE
docs(md): fix typos in CONTRIBUTING, iroha_2_whitepaper, hot-reload

### PR DESCRIPTION
**Pull request by omahs**
docs(md): fix typos in CONTRIBUTING, iroha_2_whitepaper, hot-reload

### CODE REVIEW

**Comment by nxsaken** [comment]
Hi, thanks for your contribution! 

Please fix your commit messages to follow Conventional Commits, and be more specific about where you fixed the typos.

**Review by nxsaken — CHANGES_REQUESTED** [review]
Hi, thanks for your contribution!

Please fix your commit messages to follow Conventional Commits, and be more specific about where you fixed the typos.

**Comment by nxsaken** [comment]
The PR title should be the same as the commit message if you only have one commit. `docs:` fits the commit type better in this case

**Comment by omahs** [comment]
@nxsaken Should I edit the commit message to "docs: fix typos in CONTRIBUTING.md, iroha_2_whitepaper.md and hot-reload.md"? It seems long but I can.

**Comment by nxsaken** [comment]
You can change both to `docs(md): fix typos in CONTRIBUTING, iroha_2_whitepaper, hot-reload`

**Comment by omahs** [comment]
@nxsaken Thanks for the review, just updated!

**Review by nxsaken — APPROVED** [review]

**Pull request merged**
