### PR TITLE
[WIP] Feature/peer service connection

### PR DESCRIPTION
**Pull request by MizukiSonoko**
Peer service needs grpc connection.
- [x]  Ping/pong
- [x]  fetch all transaction 
- [x]  peer service send transaction to sumeragi

### CODE REVIEW

**Comment by Warchant** [comment]
I believe copying of peer list can be done in more effective way
https://github.com/hyperledger/iroha/blob/3a8a7f378c94c5d589e9f1a50210aa424a12dc78/core/infra/config/peer_service_with_json.cpp#L103-L111

**Comment by MizukiSonoko** [comment]
Thanks for your review.  
What is your comment about?

**Comment by Warchant** [comment]
At each call of that function new copy of peerList is returned. It is some kind of deep copy. It can be performed in more elegant way :) I will look tomorrow how it can be changed

**Comment by Warchant** [comment]
I understand why you make deep copy of every field in this code:
```
std::vector<std::unique_ptr<peer::Node>> PeerServiceConfig::getPeerList() {
  initialziePeerList_from_json();

  std::vector<std::unique_ptr<peer::Node>> nodes(peerList.begin(), peerList.end());
  for (auto&& node : peerList)
    nodes.push_back(std::make_unique<peer::Node>(
        node.getIP(), node.getPublicKey(), node.getTrustScore()));
  sort(nodes.begin(), nodes.end(), [](const std::unique_ptr<peer::Node>& a,
                                      const std::unique_ptr<peer::Node>& b) {
    return a->getTrustScore() > b->getTrustScore();
  });
  return nodes;
}
```

But why we can't just sort `peerList` (which is in the same file?)
```
std::vector<peer::Node> PeerServiceConfig::peerList;

std::vector<std::unique_ptr<peer::Node>> PeerServiceConfig::getPeerList() {
  initialziePeerList_from_json();
  sort(peerList.begin(), peerList.end(), [](const std::unique_ptr<peer::Node>& a,
                                      const std::unique_ptr<peer::Node>& b) {
    return a->getTrustScore() > b->getTrustScore();
  });
  return peerList;
}
```

**Comment by satellitex** [comment]
```
// maps trust score -> peer
std::multimap<double, std::unique_ptr<peer::Node>> peerList;

std::vector<std::unique_ptr<peer::Node>> PeerServiceConfig::getPeerList() {
    return std::vector<std::unique_ptr<peer::Node>>(peerList.begin(), peerList.end());
}
```
I think it has problem.
`getPeerList` is accessed by `sumeragi` and `connection_with_grpc` from  multi thread.
When this, is it dangerous to use unique_ptr ?
Would you think how to this problem ?

**Pull request merged**
