### PR TITLE
[CI][GHActions] Cherry-pick from support/1.2.x to main - MERGE/rebase not squash to save both commits

### PR DESCRIPTION
**Pull request by kuvaldini**
- [CI][GHActions] Introduce GitHub Actions Iroha1 to main (#1028)
- [GHActions][Hotfix] Better matrix generating - fix red cross (#1039)

### CODE REVIEW

**Review by kamilsa — APPROVED** [review]

**Comment by kuvaldini** [comment]
regular comment

**Comment by kuvaldini** [comment]
regular comment

**Comment by kuvaldini** [comment]
resasvdf

**Comment by kuvaldini** [comment]
jq ars

**Comment by kuvaldini** [comment]
f an ars

**Comment by kuvaldini** [comment]
Abrcadabra

**Comment by kuvaldini** [comment]
Hello

**Comment by kuvaldini** [comment]
hello no reaction expected

**Comment by kuvaldini** [comment]
hello no reaction expected

**Pull request merged**
