### PR TITLE
Multi-plathome support based on hakodate branch

### PR DESCRIPTION
**Pull request by tkyonezu**
This is based on the hakodate branch and is compatible with multiple platforms of cloud(Linux/amd64), Mac(Linux/Darwin), Raspberry Pi (Linux/armv7l). Just type “make" you can  build and run Hyperledger Iroha, and stop it, also execution of test, and run sample programs.

Specifically, it executes as follows. Run make using the git cloned Makefile in Hyperledger Iroha's directory. Internally, the following four steps are executed.

· Bulding of iroha-docker-develop container for development
· Building Hyperledger Iroha using by iroha-docker-develop container
· Extract binaries, libraries for execution from the built hyperledger Iroha
· Building a Hyperledger Iroha container for execution from the extracted binary, library

You can also start up with "make up", stop it with "make down". By running "make test" with Hyperledger Iroha running, you can running the test program in test_bin directory.

You can also execute sample programs which using iroha-cli by executing "make up" in the example directory, running Hyperledger Iroha, and typing "make hakodate". In this case, you can refer to the execution log with "make log".

In either case, if you want to stop Hyperledger Iroha do "make down".

Especially when using Raspberry Pi, swap is used about 3 GB at build time. Therefore, it is better to prepare 4 gigabytes or more of swap using external storage.

In this version, from the original docker-compose.yml, timing issues do not correspond to wait_for like doker official. If you can not connect by "make up" by timing problem, please try again "make up”.

I hope that this PR will be useful for Hyperledger Iroha.

### CODE REVIEW

**Comment by neewy** [comment]
@tkyonezu ARMv7 is very helpful for the project. Can you please either clean this PR and leave ARM docker file in it or open a separate pull request with ARM?

**Comment by tkyonezu** [comment]
@neewy ARM support on Iroha only changes the base image of Dockerfile and docker-compose.yml.  However, it is a story if you run it in steps as I have written. Therefore, ARM support is really easy, but it may be difficult to extract it.

**Comment by tkyonezu** [comment]
As I said before, I do not think that Makefile is the best solution. Other alternatives only hope to provide an environment that can be more easily and reliably built and executed.
Also, since hakodate is only written according to the development situation of Iroha at the time, of course it is another topic whether it conforms to the current Iroha.
I pray that the environment that users are likely to make errors will be improved according to complicated procedures.

**Comment by takemiyamakoto** [comment]
Is it possible to make some progress on this pull request to get it integrated into the codebase?

**Comment by lebdron** [comment]
In order to merge this, the following has to be done:
1. Remove Makefiles, so that they will be decided over in a separate pull request.
2. Make templates for Dockerfiles and docker-compose.yml, so that it's possible to generate current files with script. Scripts can specify exactly the lines that are changed in these files, such as base images.
3. Remove Hakodate scripts, as they were removed in #686.

**Comment by tkyonezu** [comment]
There are about three issues on this pull request.

First of all, it is possible to crrespond to Raspberry Pi with docker simply by rewrite base image of Dockerfile for arm32v7.

The hakodate.sh script was created and used for the Hakodate Workshop on September 30th. I think that such a sample script is useful, but you will need to fix it following to Iroha development.

The story that there is no potability in the Makefile is something I can not understand at all. It is possible to build and run Iroha with cloud (Linux/amd64), MacOS, and Raspberry Pi just by running make with my Makefile.

It is wonderful that there is a better solution, so even if it is Ninja, real code should be provided.

What we need now is to provide Iroha with an environment that can be built and executed more easily, whether it is Makefile or Ninja.

**Pull request closed without merging**
