### PR TITLE
Feature/coverage comment

### PR DESCRIPTION
**Pull request by a-r-g-v**
## What is this pull request?

This PR adds a robot that it comments coverage to the pull request when each push event.

### CODE REVIEW

**Comment by neewy** [comment]
Can someone who had access to CircleCI communicate do the following:
"set the GitHub token to the environment variable GITHUB_TOKEN in CircleCI"

**Comment by neewy** [comment]
@Warchant added environmental variable. Can be merged

**Comment by takemiyamakoto** [comment]
Looks good.

**Comment by neewy** [comment]
We will merge feature/refactor-model first, and then this branch to test coverage

**Pull request merged**
