### PR TITLE
Adding a link for PRs from forks into CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by LiraLemur**
Signed-off-by: Sara <lira.lemur@gmail.com>

### Description of the Change
Just adding a small link

### Benefits

Some contributors might find the linked instructions useful

### Possible Drawbacks 

none

### CODE REVIEW

**Comment by neewy** [comment]
@BulatSaif do we need to trigger CI for docs? I think that in this case we can put some tags in commits, in order not to trigger CI…

**Comment by BulatSaif** [comment]
@neewy , which docs are you mean?
1. https://iroha.readthedocs.io/en/master/  
or 
2. https://docs.iroha.tech/

1- is separate service, do not triggered from CI
2- our service, can be trigger by request in new CI, by default it is trigger only for master and develop

**Comment by LiraLemur** [comment]
> 2. https://docs.iroha.tech/

I was not aware we even had that O_o 
@BulatSaif  This PR is about the first one. It builds the docs from here: https://github.com/hyperledger/iroha/tree/master/docs thus triggering the CI

**Comment by BulatSaif** [comment]
Now I understand. Yes, we can skip CI if only iroha/docs/ or  *.md files are changed.
@neewy, please, can you create the task for that

**Comment by neewy** [comment]
@BulatSaif yes <3

**Pull request merged**
