### PR TITLE
Adding missing dependencies for building iroha on Linux

### PR DESCRIPTION
**Pull request by baziorek**
### Description of the Change
I've noticed that when building according to instruction: https://iroha.readthedocs.io/en/main/build/index.html#linux dependencies are not working for minimalist debian-based distribution (to be more specific - when I'm building on docker image of `ubuntu:21.04`). So I've just added the missing dependencies.

They are helping to build on `ubuntu:21.04` docker instance, because `vcpkg` needs them. But they are not destroying building on not minimalist building on normal Ubuntu 21.04 system.

### Benefits
More automatic building on minimalist debian based linux distribution.

### Possible Drawbacks 
I've checked on normal Debian-based linux distribution and it is still installing dependencies, so rather no drawback.

### Alternate Designs *[optional]*

PS: I've also corrected formatting of python code - sphinx is ignoring tabs, so I've changed them into spaces.

### CODE REVIEW

**Comment by LiraLemur** [comment]
Looks good to me - it seems that only indentation was changed in the python code, right? 
Need an approve from the core team for the dependencies though

**Review by LiraLemur — APPROVED** [review]

**Comment by baziorek** [comment]
> Looks good to me - it seems that only indentation was changed in the python code, right?

In the python code only indentation. Because there were tabs, so I've changed them into spaces (so now copy-paste the code is easier - changing indentation after copy-paste is required)

**Comment by baziorek** [comment]
Ufff, destination branch changed from `main` into `support/1.2.x`

**Comment by kuvaldini** [comment]
@baziorek is it still actual?
please try build in Docker `$ docker pull ghcr.io/hyperledger/iroha-builder:support/1.2.x`

All dependancies are listed in `./docker/iroha-builder/Dockerfile`.  If this problem still reproducible please rebase and prepare to review. If not let's close this PR

**Comment by baziorek** [comment]
> @baziorek is it still actual?
> please try build in Docker `$ docker pull ghcr.io/hyperledger/iroha-builder:support/1.2.x`
> 
> All dependancies are listed in `./docker/iroha-builder/Dockerfile`. If this problem still reproducible please rebase and prepare to review. If not let's close this PR

Sorry for not replying for few days - I didn't see Your message.

I've tried command as You suggested and few more, they are invalid:
```
# command as You told me is not working:
➜  ~ docker pull ghcr.io/hyperledger/iroha-builder:support/1.2.x
invalid reference format
# so I've tried:
➜  ~ docker pull hyperledger/iroha-builder:support/1.2.x 
invalid reference format
# I've also tried command from DockerHub: https://hub.docker.com/r/hyperledger/iroha-builder
➜  ~ docker pull hyperledger/iroha-builder              
Using default tag: latest
Error response from daemon: manifest for hyperledger/iroha-builder:latest not found: manifest unknown: manifest unknown
__________
The problem, which I'm trying to solve is when I don't use default docker image with iroha, but when I'm pulling `ubuntu:21.04` from docker then building Iroha by my own.

**Comment by baziorek** [comment]
I see conflicts are killing the PR again and again. Fortunately @petermetz repaired the same thing in different PR: https://github.com/hyperledger/iroha/pull/1393
So I'm closing my PR.

**Comment by petermetz** [comment]
> I see conflicts are killing the PR again and again. Fortunately @petermetz repaired the same thing in different PR: #1393
> So I'm closing my PR.

@baziorek Oops, sorry for the duplicate! I'm happy to withdraw my PR in favor of yours, just let me know!

**Comment by baziorek** [comment]
> @baziorek Oops, sorry for the duplicate! I'm happy to withdraw my PR in favor of yours, just let me know!

@petermetz No problem. It is good as it is now when my PR is closed (it has 558 conflicted files:D).

**Pull request closed without merging**
