### PR TITLE
Use pubkey as identifier in SignatureSetType

### PR DESCRIPTION
**Pull request by l4l**
### Description of the Change

ed25519 can have different signature for the same public key, so it necessary to guarantee uniqueness of each public key in signature set

### CODE REVIEW

**Comment by neewy** [comment]
This fix should contain test with text data based on modified version of ed25519

**Comment by l4l** [comment]
It is not really trivial to write the test for that case, as long as:
1. requires modification of iroha-ed25519
2. or there's a need somehow skip timeout check (that is not trivial at all)

**Comment by l4l** [comment]
Good idea, thanks! I will finish it soon

**Comment by neewy** [comment]
Any progress? I've noticed you have added test in commit above, is it sufficient to review this fix?

**Comment by l4l** [comment]
Yes, for now only that test can be done without significant projects changes and I think better review&merge it asap, then think about other components (though, they will work as well, as they have code duplication actually)

**Pull request merged**
