### PR TITLE
Trying to upgrade libraries in VCPKG

### PR DESCRIPTION
**Pull request by baziorek**
## Description
In PR https://github.com/hyperledger/iroha/pull/3852/ I needed to revert upgrading VCPKG. It caused libraries to downgrade. So now we need to try to upgrade libraries manually one by one.

Corrections (marked as [x] when CI passed):
- [x] iroha-ed25519 (no updates)
- [x] protobuf 3.15.8 -> 3.21.12
- [x] abseil 2021-03-24 -> 20230125.0
- [x] benchmark 1.5.2 -> 1.7.1
- [x] gflags 2.2.2-1 -> 2.2.2#5
- [x] nlohmann-json 3.9.1 -> 3.11.2
- [x] rapidjson 2020-09-14 -> 2022-06-28#3
- [x] rxcpp 4.1.0-1 -> 4.1.1#1
- [x] rocksdb 6.14.6 -> 7.9.2
- [ ] fmt 7.1.3#4 -> 9.1.0#1 - PROBLEM with upgrading library with patch
- [ ] spdlog 1.8.5#2 -> 1.11.0 - PROBLEM with upgrading library with patch
- [ ] gtest 1.10.0#4 -> 1.13.0 - PROBLEM with upgrading library with patch
- [ ] grpc 1.37.0#1 -> 1.51.1 - PROBLEM with upgrading library with patch
- [ ] soci[boost,postgresql] - PROBLEM with upgrading library with patch
- [ ] prometheus-cpp 0.12.2 -> 1.1.0 - PROBLEM with upgrading library with patch
- [ ] boost-* - PROBLEM with upgrading library with patch

### Linked issue

Closes #{issue_number} 

### Benefits
Newer packages - it will compile longer, less bugs, more security etc.

### Checklist

- [ ] I've read `CONTRIBUTING.md`
- [ ] I've used the standard signed-off commit format (or will squash just before merging)
- [ ] All applicable CI checks pass (or I promised to make them pass later)
- [ ] (optional) I've written unit tests for the code changes
- [ ] I replied to all comments after code review, marking all implemented changes with thumbs up

# More information:
I was using the tutorial (as inspiration): https://stackoverflow.com/questions/72588408/vcpkg-how-to-edit-package-file-when-compilation-fails-when-installing-package
1. First I've build all packages with VCPKG in newest versions (details: https://github.com/hyperledger/iroha/pull/3852)
2. Then I used older version of vcpkg (+ packages).
3. I've created repository in `./vcpkg-build`
4. For each patch I've used the function:
```
function update_library
{
    # this function should be run in vcpkg-build directory, where sub-repository is initialised 
    # according to: https://stackoverflow.com/questions/72588408/vcpkg-how-to-edit-package-file-when-compilation-fails-when-installing-package
    library_name=$1
    source_directory_name_to_copy_files='vcpkg-build_newest' # remember to set proper name
    echo "Trying to update: $library_name, from version: $(./vcpkg list | grep $library_name)"
    
    rm ports/${library_name}/*
    cp ../${source_directory_name_to_copy_files}/ports/${library_name}/* ports/${library_name}/
    git add ports/${library_name}/
    git status
    git diff --cached > ../vcpkg/patches/upgrade_${library_name}_to_.patch
    git reset --hard
}
# example:
update_library protobuf
```

### CODE REVIEW

**Comment by baziorek** [comment]
# Summary

Some libraries can be updated with patches, but not all of them can be upgraded that way. Rest of libraries needs to be updates by vcpkg upgrade. Unfortunately, just vcpkg upgrade is breaking compilation, so for now IMO it is better to leave like that.

After upgrades of 8 libraries, Iroha 1 still compiles and CI is passing. But I'm not sure if it hasn't broken anything. That is why IMO it is better to make release 1.6.0 without the PR, but the PR can be 1.6.1.

**Comment by Arjentix** [comment]
@baziorek , sorry for such a big delay. Looks like I will be the one who will review your PR as I have C++ experience and have already reviewed your another work.

However, please, keep in mind that I'm Iroha 2 developer and know pretty much nothing about Iroha 1, so don't mind correcting me if I'll be wrong.
Same goes for my C++ skills which I haven't used for more than a year....

**Review by Arjentix — APPROVED** [review]

**Comment by baziorek** [comment]
> @baziorek , sorry for such a big delay. Looks like I will be the one who will review your PR as I have C++ experience and have already reviewed your another work.
> 
> However, please, keep in mind that I'm Iroha 2 developer and know pretty much nothing about Iroha 1, so don't mind correcting me if I'll be wrong. Same goes for my C++ skills which I haven't used for more than a year....

Thanks for approving the PR. In the PR there are only libraries upgrades, so if it compiles it will work (as long as libraries do not change their behaviour).

@Arjentix Should I wait for second approve, or it can be merged?

**Comment by Arjentix** [comment]
@baziorek , you can merge

**Pull request merged**
