### PR TITLE
docs(build): add zip and pkg-config to list of build deps

### PR DESCRIPTION
**Pull request by petermetz**
### Description of the Change

These were also missing from my WSL 2 Ubuntu 20.04 installation
and had to install them manually before I could build the project
successfully.

Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>

### Benefits

For people who already have those deps, this will make no difference, but it will save extra steps for those who use an OS distribution where zip and pkg-config are not present.

### Possible Drawbacks

None.

### Usage Examples or Tests *[optional]*

N/A

### Alternate Designs *[optional]*

N/A

### CODE REVIEW

**Review by kuvaldini — APPROVED** [review]

**Comment by kuvaldini** [comment]
Please set target branch `develop`

**Comment by petermetz** [comment]
> Please set target branch `develop`

@kuvaldini Rebased it just now, thanks for the info.

**Comment by petermetz** [comment]
cc: @LiraLemur  @baziorek

**Review by baziorek — APPROVED** [review]
> cc: @LiraLemur @baziorek

I fully agree with the changes - I was trying to solve the same problem in different PR: https://github.com/hyperledger/iroha/pull/1076 (closed now).

I faced the problem when I was building iroha on newly downloaded Ubuntu docker image - those dependencies are missing.

**Comment by baziorek** [comment]
I've tried really hard, but unfortunately I can't win with the DCO problems in this PR, I was trying really hard, I used suggested commands from github, without success. So probably I'd have to create similar PR with the same changes, but after merging my PRs: https://github.com/hyperledger/iroha/pull/1662
______
Details what I've tried:
[DCO problem in MR.pdf](https://github.com/hyperledger/iroha/files/7792241/DCO.problem.in.MR.pdf)

**Review by iceseer — APPROVED** [review]

**Pull request merged**
