### PR TITLE
refactor!: remove `max` prefix from `blocks_in_memory`

### LINKED ISSUE #5108: Rename `max_blocks_in_memory` to `blocks_in_memory`
It's obvious that number of blocks in memory is `min(total_block_count, blocks_in_memory)`

### PR DESCRIPTION
**Pull request by mversic**
closes #5108

### CODE REVIEW

**Review by 0x009922 — CHANGES_REQUESTED** [review]
Please update `peer.template.toml` too.

**Review by 0x009922 — CHANGES_REQUESTED** [review]
And it seems this parameter is not covered in `*.toml` in fixures. Could you add it there and ensure it passes?

**Comment by 0x009922** [comment]
@BAStos525

**Comment by mversic** [comment]
> And it seems this parameter is not covered in `*.toml` in fixures. Could you add it there and ensure it passes?

done

**Review by Erigara — APPROVED** [review]

**Review by 0x009922 — APPROVED** [review]

**Pull request merged**
