### PR TITLE
Feature/immutable interfaces

### PR DESCRIPTION
**Pull request by muratovv**
## What is this pull request?
This pr provides a draft of the new style immutable model.
Immutable model important part of Iroha development, because it may save models' invariants in runtime without violation.
   
## Why do you implement it? Why do we need this pull request?
Currently, this PR focused on general interfaces, namespaces, and folders.

## Details/Features
* Template base class for guarantee basic interface, such as deep copy, to string and etc
* Backward compatibility - all model object should be converted to old-fashion objects for painless transition to the new model
* Commands and queries are final classes, that keep variant inside
* Non-trivial fields wrapped with using for further type-decoupling purposes

## Additional dependencies (optional)
Library required:
* old-fashion model
* boost::variant

### CODE REVIEW

**Comment by Warchant** [comment]
Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[shared_model/CMakeLists.txt, line 23 at r1](https://reviewable.io:443/reviews/hyperledger/iroha/647#-Kwubw3uCt2HCpXO3D59:-Kwubw3uCt2HCpXO3D5A:b-u3vpzx) ([raw file](https://github.com/hyperledger/iroha/blob/c68ff0700ee32423a1e2dafa48f34497a092f650/shared_model/CMakeLists.txt#L23)):*
> ```CMake
> 
> 
> SET(EXECUTABLE_OUTPUT_PATH ${PROJECT_BINARY_DIR}/shared_model_bin)
> ```

There are no binaries. Use LIBRARY_OUTPUT_PATH

---

*[shared_model/interfaces/polymorphic_wrapper.hpp, line 56 at r1](https://reviewable.io:443/reviews/hyperledger/iroha/647#-Kwuca2tmr0WkotPyzLw:-Kwuca2tmr0WkotPyzLx:bg2qgz1) ([raw file](https://github.com/hyperledger/iroha/blob/c68ff0700ee32423a1e2dafa48f34497a092f650/shared_model/interfaces/polymorphic_wrapper.hpp#L56)):*
> ```cpp
> 
>       /**
>        * Move copy constructor
> ```

no `move copy constructor`

should be `move constructor`

---

*[shared_model/interfaces/polymorphic_wrapper.hpp, line 59 at r1](https://reviewable.io:443/reviews/hyperledger/iroha/647#-Kwud9z3skLo9HZgtVDn:-Kwud9z3skLo9HZgtVDo:b3lmoge) ([raw file](https://github.com/hyperledger/iroha/blob/c68ff0700ee32423a1e2dafa48f34497a092f650/shared_model/interfaces/polymorphic_wrapper.hpp#L59)):*
> ```cpp
>        * @param rhs - wrapped temporary value
>        */
>       PolymorphicWrapper(PolymorphicWrapper &&rhs) {
> ```

move constructor should be marked noexcept

---

*[shared_model/interfaces/polymorphic_wrapper.hpp, line 69 at r1](https://reviewable.io:443/reviews/hyperledger/iroha/647#-Kwud-Jq_38mxHBNrdZT:-Kwud-Jq_38mxHBNrdZU:b-1ay7wl) ([raw file](https://github.com/hyperledger/iroha/blob/c68ff0700ee32423a1e2dafa48f34497a092f650/shared_model/interfaces/polymorphic_wrapper.hpp#L69)):*
> ```cpp
>        */
>       PolymorphicWrapper &operator=(const PolymorphicWrapper &rhs) {
>         ptr = std::shared_ptr<T>(rhs.ptr.get()->copy());
> ```

change to ptr->copy()

---

*[shared_model/interfaces/polymorphic_wrapper.hpp, line 78 at r1](https://reviewable.io:443/reviews/hyperledger/iroha/647#-Kwud57KlddlV1CMvr8I:-Kwud57KlddlV1CMvr8J:b-7krqyc) ([raw file](https://github.com/hyperledger/iroha/blob/c68ff0700ee32423a1e2dafa48f34497a092f650/shared_model/interfaces/polymorphic_wrapper.hpp#L78)):*
> ```cpp
>        * @return *this
>        */
>       PolymorphicWrapper &operator=(PolymorphicWrapper &&rhs) {
> ```

move operator should be marked noexcept

---

*[shared_model/interfaces/polymorphic_wrapper.hpp, line 86 at r1](https://reviewable.io:443/reviews/hyperledger/iroha/647#-KwudELliUwiGI9IomTS:-KwudELliUwiGI9IomTT:b-93ufc0) ([raw file](https://github.com/hyperledger/iroha/blob/c68ff0700ee32423a1e2dafa48f34497a092f650/shared_model/interfaces/polymorphic_wrapper.hpp#L86)):*
> ```cpp
>        * Checks equality of objects inside
>        * @param rhs - other wrapped value
>        * @return true, if wpapped objects are same
> ```

wrapped

---

*[shared_model/interfaces/primitive.hpp, line 29 at r1](https://reviewable.io:443/reviews/hyperledger/iroha/647#-Kwue2PYO5bku63WF-Oj:-Kwue2PYO5bku63WF-Ok:baj5j7u) ([raw file](https://github.com/hyperledger/iroha/blob/c68ff0700ee32423a1e2dafa48f34497a092f650/shared_model/interfaces/primitive.hpp#L29)):*
> ```cpp
>     /**
>      * Primitive is a base class of whole domain objects in system.
>      * This class required for guarantee consistent interface on whole model
> ```

on whole -> on all

---

*[shared_model/interfaces/primitive.hpp, line 35 at r1](https://reviewable.io:443/reviews/hyperledger/iroha/647#-KwuePB3yLJxoO6hcgr0:-KwuePB3yLJxoO6hcgr1:bg1vdbt) ([raw file](https://github.com/hyperledger/iroha/blob/c68ff0700ee32423a1e2dafa48f34497a092f650/shared_model/interfaces/primitive.hpp#L35)):*
> ```cpp
>      */
>     template <typename Model, typename OldModel>
>     class Primitive {
> ```

no virtual destructor in this class

---

*[shared_model/interfaces/transaction.hpp, line 36 at r1](https://reviewable.io:443/reviews/hyperledger/iroha/647#-KwueZvezT9mVO3dPjjV:-KwueZvezT9mVO3dPjjW:bg1vdbt) ([raw file](https://github.com/hyperledger/iroha/blob/c68ff0700ee32423a1e2dafa48f34497a092f650/shared_model/interfaces/transaction.hpp#L36)):*
> ```cpp
>      * state of ledger.
>      */
>     class Transaction
> ```

no virtual destructor in this class

---

*[shared_model/interfaces/commands/add_asset_quantity.hpp, line 32 at r1](https://reviewable.io:443/reviews/hyperledger/iroha/647#-Kwuex1DYiBKqbCEayGH:-Kwuex1DYiBKqbCEayGI:bg1vdbt) ([raw file](https://github.com/hyperledger/iroha/blob/c68ff0700ee32423a1e2dafa48f34497a092f650/shared_model/interfaces/commands/add_asset_quantity.hpp#L32)):*
> ```cpp
>      * TODO add business logic description
>      */
>     class AddAssetQuantity
> ```

no virtual destructor in this class

---

*[shared_model/interfaces/commands/command.hpp, line 37 at r1](https://reviewable.io:443/reviews/hyperledger/iroha/647#-KwufEbWYVQyTgP7PYcM:-KwufEbWYVQyTgP7PYcN:b2or9bb) ([raw file](https://github.com/hyperledger/iroha/blob/c68ff0700ee32423a1e2dafa48f34497a092f650/shared_model/interfaces/commands/command.hpp#L37)):*
> ```cpp
>      * avoid this misunderstanding class should be final
>      */
>     class Command final : public Primitive<Command, iroha::model::Command> {
> ```

no virtual destructor in this class (should override the one from Primitive)

---

*[shared_model/interfaces/common_objects/hash.hpp, line 28 at r1](https://reviewable.io:443/reviews/hyperledger/iroha/647#-Kwuf_5xCA9xpNoozPp2:-Kwuf_5xCA9xpNoozPp3:bg1vdbt) ([raw file](https://github.com/hyperledger/iroha/blob/c68ff0700ee32423a1e2dafa48f34497a092f650/shared_model/interfaces/common_objects/hash.hpp#L28)):*
> ```cpp
>   namespace interface {
>     // TODO discuss naming, may be blob will be more applicable
>     class Hash : public Primitive<Hash, Hash> {
> ```

no virtual destructor in this class

---

*[shared_model/interfaces/common_objects/hash.hpp, line 32 at r1](https://reviewable.io:443/reviews/hyperledger/iroha/647#-Kwufg2QUdIlfjNvghTO:-Kwufg2R-bRYPqLfsq5Q:bgnx3e7) ([raw file](https://github.com/hyperledger/iroha/blob/c68ff0700ee32423a1e2dafa48f34497a092f650/shared_model/interfaces/common_objects/hash.hpp#L32)):*
> ```cpp
>        * @return provides raw representation of hash
>        */
>       virtual const std::string &blobRepr() const = 0;
> ```

maybe it is better to call it `toBlob`? 

---

*[shared_model/interfaces/common_objects/hash.hpp, line 37 at r1](https://reviewable.io:443/reviews/hyperledger/iroha/647#-Kwufia61OgaN2TkvlMv:-Kwufia61OgaN2TkvlMw:b7rhcpi) ([raw file](https://github.com/hyperledger/iroha/blob/c68ff0700ee32423a1e2dafa48f34497a092f650/shared_model/interfaces/common_objects/hash.hpp#L37)):*
> ```cpp
>        * @return provides human-readable representation of hash
>        */
>       virtual const std::string &hexRepr() const = 0;
> ```

toHexstring?
toHex?

---

*[shared_model/interfaces/common_objects/signature.hpp, line 30 at r1](https://reviewable.io:443/reviews/hyperledger/iroha/647#-KwufnjSYiF6aSr4f3kN:-KwufnjSYiF6aSr4f3kO:b-diqtq0) ([raw file](https://github.com/hyperledger/iroha/blob/c68ff0700ee32423a1e2dafa48f34497a092f650/shared_model/interfaces/common_objects/signature.hpp#L30)):*
> ```cpp
>      * Class represents signature of high-level domain objects.
>      */
>     class Signature : public Primitive<Signature, iroha::model::Signature> {
> ```

no virtual destructor

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hyperledger/iroha/647)*

**Comment by Warchant** [comment]
Reviewed 2 of 20 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hyperledger/iroha/647)*

**Comment by lebdron** [comment]
>move constructor should be marked noexcept

There is no such requirement
http://en.cppreference.com/w/cpp/language/move_assignment

**Comment by l4l** [comment]
Review status: 15 of 20 files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---

*[shared_model/interfaces/polymorphic_wrapper.hpp, line 59 at r4](https://reviewable.io:443/reviews/hyperledger/iroha/647#-Kx-9iOeKQc_OII-Dx42:-Kx-9iOeKQc_OII-Dx43:b8fmdld) ([raw file](https://github.com/hyperledger/iroha/blob/57f74f5cf05e1d1a12f85876e5ffc221e844099d/shared_model/interfaces/polymorphic_wrapper.hpp#L59)):*
> ```cpp
>        */
>       PolymorphicWrapper(PolymorphicWrapper &&rhs) noexcept {
>         std::swap(this->ptr, rhs.ptr);
> ```

`this->ptr` is undefined, so its swapping is a bad idea. Imo it's better to use smth like:
```
PolymorphicWrapper(PolymorphicWrapper &&rhs) ptr(0) {
  std::swap(ptr, rhs.ptr);
}
```

---

*[shared_model/interfaces/polymorphic_wrapper.hpp, line 78 at r4](https://reviewable.io:443/reviews/hyperledger/iroha/647#-Kx-BNh_jfhlYomTjfRB:-Kx-BNh_jfhlYomTjfRC:bw3hnfj) ([raw file](https://github.com/hyperledger/iroha/blob/57f74f5cf05e1d1a12f85876e5ffc221e844099d/shared_model/interfaces/polymorphic_wrapper.hpp#L78)):*
> ```cpp
>        */
>       PolymorphicWrapper &operator=(PolymorphicWrapper &&rhs) noexcept {
>         std::swap(this->ptr, rhs.ptr);
> ```

Same as the previous

---

*[shared_model/interfaces/transaction.hpp, line 117 at r4](https://reviewable.io:443/reviews/hyperledger/iroha/647#-Kx-Cd3Qo8JJ3nbo9FEU:-Kx-Cd3Qo8JJ3nbo9FEV:b-5jva8v) ([raw file](https://github.com/hyperledger/iroha/blob/57f74f5cf05e1d1a12f85876e5ffc221e844099d/shared_model/interfaces/transaction.hpp#L117)):*
> ```cpp
> 
>       iroha::model::Transaction *makeOldModel() const {
>         // TODO implement conversion to old style transaction
> ```

Maybe then it's better to name it cast or convert rather than make?

---

*[shared_model/interfaces/commands/command.hpp, line 68 at r4](https://reviewable.io:443/reviews/hyperledger/iroha/647#-Kx-D8Q0PKO95paFi6fJ:-Kx-D8Q0PKO95paFi6fK:b-wt5fgp) ([raw file](https://github.com/hyperledger/iroha/blob/57f74f5cf05e1d1a12f85876e5ffc221e844099d/shared_model/interfaces/commands/command.hpp#L68)):*
> ```cpp
>       using CommandListType = decltype(command_variant)::types;
> 
>       std::string toString() const override {
> ```

Maybe it's a good idea to make in consistent with the stl (`to_string`)? But it brings chaos to naming thoug

---

*[shared_model/interfaces/common_objects/hash.hpp, line 32 at r1](https://reviewable.io:443/reviews/hyperledger/iroha/647#-Kwufg2QUdIlfjNvghTO:-Kx-DSiHP3WOaiTEfPQs:b-jo0dib) ([raw file](https://github.com/hyperledger/iroha/blob/c68ff0700ee32423a1e2dafa48f34497a092f650/shared_model/interfaces/common_objects/hash.hpp#L32)):*
<details><summary><i>Previously, Warchant (Bogdan) wrote…</i></summary><blockquote>

maybe it is better to call it `toBlob`? 
</blockquote></details>

imo blob is better

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hyperledger/iroha/647)*

**Comment by l4l** [comment]
Reviewed 13 of 20 files at r1, 2 of 4 files at r2, 1 of 1 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hyperledger/iroha/647)*

**Comment by l4l** [comment]
:lgtm:

---

Review status: 14 of 21 files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hyperledger/iroha/647#-:-Kx7v0d-iQbMCxwNr7Gn:bnfp4nl)*

**Comment by l4l** [comment]
:lgtm:
btw, why in some classes firstly goes private section then public? https://google.github.io/styleguide/cppguide.html#Declaration_Order (note that it's "usually", not "required")

---

Reviewed 7 of 7 files at r5.
Review status: all files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hyperledger/iroha/647#-:-Kx7vDp5t1kvCkfIERvB:b-awli31)*

**Pull request merged**
