### PR TITLE
Updates to requirements

### PR DESCRIPTION
**Pull request by bhaskarvilles**
upgrade the packages in requirements.txt

### CODE REVIEW

**Comment by bhaskarvilles** [comment]
Can any one merge this request ?

**Comment by bhaskarvilles** [comment]
Anny one ?

**Comment by appetrosyan** [comment]
Hello, we've been having some CI issues. They are resolved, but some of the checks are still failing. Unfortunately we can't merge as is, so you'll have to bear with us a while longer.

**Comment by bhaskarvilles** [comment]
What happened to CI pipelines ?

**Comment by appetrosyan** [comment]
Long story. But the CI runs on a custom AWS matrix, and it often drops the task which looks like a failed pipeline.

**Comment by bhaskarvilles** [comment]
Migrate to Circle CI pipelines then, i see many HyperLedger Projects out using Circle CI platform.

**Comment by bhaskarvilles** [comment]
> Migrate to Circle CI pipelines then, i see many HyperLedger Projects out using Circle CI platform.

Btw I'm inviting you as collaborators for the code to fix the problem. Please don't mind.

**Comment by appetrosyan** [comment]
> Migrate to Circle CI pipelines then, i see many HyperLedger Projects out using Circle CI platform.

We'd like to, but we'd have to agree on that with hyperledger. @ryjones what do you think?

**Comment by ryjones** [comment]
> We'd like to, but we'd have to agree on that with hyperledger. @ryjones what do you think?

Please don't. We're trying to get away from Circle CI as fast as possible.

**Comment by bhaskarvilles** [comment]
> > We'd like to, but we'd have to agree on that with hyperledger. @ryjones what do you think?
> 
> Please don't. We're trying to get away from Circle CI as fast as possible.

Why ? Maybe Azure or GitHub, GitLab will be more helpful in this.

**Comment by appetrosyan** [comment]
Sorry didn't mean to stir up controversy.

**Comment by ryjones** [comment]
> Sorry didn't mean to stir up controversy.

No worries!

**Comment by bhaskarvilles** [comment]
So my contributions will not be pushed ?

**Comment by appetrosyan** [comment]
Oh they will, I think we can ask the DevOps to merge this without passing checks, since you clearly didn't change any code.

**Review by appetrosyan — APPROVED** [review]

**Pull request merged**
