### PR TITLE
Task/sumeragi json format error

### PR DESCRIPTION
**Pull request by motxx**
- Sorry, I can't solve circle-ci error `docker run -p 1204:1204 hyperledger/iroha-docker /test.sh`

- Created sumeragi.json format checker
    - It ensures valid nested json keys, values and types of values of sumeragi.json.
    - Example
        - `ensureKeyValueFormat<ValueType>(jsonObject, {"hoge", "foo", "fuga"}, 0)` verifies the format of json `{"hoge":{"foo":{"fuga":"value"}}}`
        - `{"me":{"iP": "172.17.0.4", ...}}` can be detected and it shows warning `Type mismatch "ip" in "me"`
        - `{"me":{"ip": "172.17.0.999", ...}}` can be detected and it shows warning of invalid IP addr message.
    - Not implemented
        - find keys that sumeragi.json does not use.
            - e.g. In sumeragi.json, text including `{"uselessKey","12345"}` cannot be detected.
        - verify whether valid base64 encoded string (publicKey) or not.

### CODE REVIEW

**Comment by tkyonezu** [comment]
Thx motxxx for developing this features in IROHA.  In the not implemented features, unused key check is useful and need in IROHA. And, I think verify base64 strings will be done at later time in IROHA, in which IROHA nodes are verified by those public key.  So, it does'nt need in this time.

**Comment by motxx** [comment]
Sorry, I think it's ugly that json format is hard coding. It's better to prepare a basic format JSON file and compare config files with it. Then, unused key check feature is also solved at the same time, I think.

- Sample of basic_sumeragi.json file
```
{
  "me":{
    "ip":"ip",
    "name":"*",
    "publicKey":"*",
    "privateKey":"*"
  },
  "group":[
    {
      "ip":"ip",
      "name":"*",
      "publicKey":"*"
    }
  ]
}
```

- Sample of regex_def.json file
```
{
  "ip" : "^(([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]).){3}([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$"
}
```

**Comment by motxx** [comment]
> In the not implemented features, unused key check is useful and need in IROHA.
> to prepare a basic format JSON file and compare config files with it.
I dealt with these issues.

I could not deal with loading `regex_def.json` because nlohmann/json does not support to read symbols used in regular expression.

**Comment by Warchant** [comment]
I will look.

**Comment by motxx** [comment]
Thank you for looking. My local test has passed. I suppose the program cannot read the test files. I will investigate it.

**Comment by Warchant** [comment]
This is what I've got after local build:
```
bogdan@private ~/tools/iroha/build/test_bin $ ./ensure_sumeragi_json_format_test 
Running main() from gtest_main.cc
[==========] Running 5 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 5 tests from ensure_sumeragi_json_format
[ RUN      ] ensure_sumeragi_json_format.normal_sumeragi_json
1486128144 INFO [peer with json] load json is {
  "me":{
    "ip":"ip",
    "name":"*",
    "publicKey":"publicKey",
    "privateKey":"privateKey"
  },
  "group":[
    {
      "ip":"ip",
      "name":"*",
      "publicKey":"publicKey"
    }
  ]
}
[       OK ] ensure_sumeragi_json_format.normal_sumeragi_json (30 ms)
[ RUN      ] ensure_sumeragi_json_format.bad_json
[       OK ] ensure_sumeragi_json_format.bad_json (2 ms)
[ RUN      ] ensure_sumeragi_json_format.bad_ip
1486128144 WARNING [peer service with json] IP 172.17.0.987 looks like not a valid ip.
1486128144 WARNING [peer service with json] IP 172.17.0.4. looks like not a valid ip.
[       OK ] ensure_sumeragi_json_format.bad_ip (25 ms)
[ RUN      ] ensure_sumeragi_json_format.missing_key

/home/bogdan/tools/iroha/test/infra/config/inputs/no_group_ip.json
1486128144 WARNING [peer service with json] Not found: ip

/home/bogdan/tools/iroha/test/infra/config/inputs/no_group_name.json
1486128144 WARNING [peer service with json] Not found: name

/home/bogdan/tools/iroha/test/infra/config/inputs/no_group_publicKey.json
1486128144 WARNING [peer service with json] Not found: publicKey

/home/bogdan/tools/iroha/test/infra/config/inputs/no_me_ip.json
1486128144 WARNING [peer service with json] Not found: ip

/home/bogdan/tools/iroha/test/infra/config/inputs/no_me_name.json
1486128144 WARNING [peer service with json] Not found: name

/home/bogdan/tools/iroha/test/infra/config/inputs/no_me_privateKey.json
1486128145 WARNING [peer service with json] Not found: privateKey

/home/bogdan/tools/iroha/test/infra/config/inputs/no_me_publicKey.json
1486128145 WARNING [peer service with json] Not found: publicKey
[       OK ] ensure_sumeragi_json_format.missing_key (90 ms)
[ RUN      ] ensure_sumeragi_json_format.useless_key

/home/bogdan/tools/iroha/test/infra/config/inputs/useless_me_key.json
1486128145 WARNING [peer service with json] Unused keys: aaaa

/home/bogdan/tools/iroha/test/infra/config/inputs/useless_group_key.json
1486128145 WARNING [peer service with json] Unused keys: key123456
[       OK ] ensure_sumeragi_json_format.useless_key (27 ms)
[----------] 5 tests from ensure_sumeragi_json_format (174 ms total)

[----------] Global test environment tear-down
[==========] 5 tests from 1 test case ran. (175 ms total)
[  PASSED  ] 5 tests.
```

**Comment by motxx** [comment]
Thank you. And this output is what I have expected.

**Comment by Warchant** [comment]
`test.sh` uses return code to determine if test failed or not. 
Your code returns 1 (exit failure, bad json), so `test.sh` thinks that test has failed. 

If test completes with success, make sure you return 0.

Also, some of these files are changed in `feature/refactoring` branch, make sure you pull it before accepting pull request.

**Pull request closed without merging**
