### PR TITLE
vcpkg Linux integration

### PR DESCRIPTION
**Pull request by lebdron**
### Description of the Change
- Add necessary changes to CMake files to enable vcpkg build on Linux
- Remove unused `dependencies` Dockerfile
- Add vcpkg Dockerfile
- Bump vcpkg version, add necessary packages, add patch which provides iroha-ed25519

### Benefits
Simpler dependency management and Dockerfile

### Possible Drawbacks 
Not supported on Linux arm and aarch64 at the moment

### CODE REVIEW

**Comment by igor-egorov** [comment]
Tests with TYPED_TEST_CASE cannot be built on macos (appleclang) using vcpkg.
If this is not a stopper, I am going approve the change.

**Comment by lebdron** [comment]
@igor-egorov They will build soon, fixes are in progress

**Comment by igor-egorov** [comment]
so let's wait for the fixes, right?

**Comment by igor-egorov** [comment]
ci can't compile on linux(

**Comment by lebdron** [comment]
@igor-egorov Working on it 👀

**Comment by lebdron** [comment]
multisig_tx_pipeline_test failed on Mac, but this test is currently known to be unstable.

**Pull request merged**
