### PR TITLE
Add readthedocs.org build status

### PR DESCRIPTION
**Pull request by neewy**
[ci skip]

Signed-off-by: Nikolay Yushkevich <n.yushkevich@hotmail.com>

### CODE REVIEW

**Comment by neewy** [comment]
@LiraLemur can you please jump in and help with styling and proper alignment? Thanks!

**Comment by LiraLemur** [comment]
@neewy please check if you like my idea

**Comment by neewy** [comment]
@LiraLemur can we format it somehow so that it occupies less vertical space? e.g. table in all-contributors: https://github.com/all-contributors/all-contributors#emoji-key

**Comment by neewy** [comment]
It it better to reformat this table in two rows

**Comment by LiraLemur** [comment]
Fixed the table

**Pull request merged**
