### PR TITLE
[fix] #0000: Fix executor downloading in update_configs.sh

### PR DESCRIPTION
**Pull request by Arjentix**
### Linked issue

Closes #{issue_number} 

### Checklist

- [x] I've read `CONTRIBUTING.md`
- [x] I've used the standard signed-off commit format (or will squash just before merging)
- [x] All applicable CI checks pass (or I promised to make them pass later)
- [ ] (optional) I've written unit tests for the code changes
- [ ] I replied to all comments after code review, marking all implemented changes with thumbs up

### CODE REVIEW

**Review by pesterev — APPROVED** [review]

**Comment by pesterev** [comment]
The title needs to be corrected.

**Comment by Arjentix** [comment]
> The title needs to be corrected.

I thought that's a valid name :(

Do I have to specify issue number now? @mversic ?

**Review by 0x009922 — APPROVED** [review]

**Comment by 0x009922** [comment]
> Do I have to specify issue number now

`#0000` might be a workaround, if we cannot ignore the action.

**Review by mversic — APPROVED** [review]

**Comment by mversic** [comment]
> > The title needs to be corrected.
> 
> I thought that's a valid name :(
> 
> Do I have to specify issue number now? @mversic ?

only `[refactor]` doesn't need ticket number

**Pull request merged**
