### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by neewy**
### Description of the Change

We have changed the CVS schema.

### Benefits

Increased awareness of contributors.

### Possible Drawbacks 

None

### CODE REVIEW

**Comment by l4l** [comment]
Merge is for maintainers, not for contributors, why it should be here?

**Comment by muratovv** [comment]
Who is the consumer of CONTRIBUTING.md file? I mean this information for maintainers or for contributors only. If second, there are no reasons to write about merging to base branch.

**Comment by Warchant** [comment]
CONTRIBUTORS.md file is for all contributors, especially for the new ones.

IMO this scheme is bad:
1. reviewer will not know that developer failed with merge (wrongly resolved merge conflicts, for instance), therefore develop will be much more often in "failed" condition.
2. for developer there is no way to run CI and check all postconditions (builds on mac, builds on linux, tests are executed, etc). Locally you can execute only one step amount many. Working on mac, how can you be sure that your changes will work properly on ARM?

**Comment by neewy** [comment]
I have closed this PR since the decision about VCS handling schema was not fixed. IMO we have to make it clear in this file, and since we tried merges only and I find (not only me though) comments of @Warchant valid, we need to use old approach with rebases + maybe squash & merge for trunks at least per a sprint. 

I will assign the discussion

**Pull request closed without merging**
