### PR TITLE
Docs Boost update

### PR DESCRIPTION
**Pull request by itorK**
Signed-off-by: Karol Przybylski <karol.przybylski@esm-technology.pl>

### Description of the Change

Update documentation for newest Boost.

### Benefits

Could compile with boost >1.68

### Possible Drawbacks 

None

### CODE REVIEW

**Comment by itorK** [comment]
You're right, I commited 6 hours after #1680  :)
Enviroment vars is needed when you compiled boost in your custom directory.

**Comment by nickaleks** [comment]
@itorK Isn't BOOST_ROOT enough for cmake? I believe CMake is able to deduce include directory from that.

**Comment by l4l** [comment]
Could you please review @nickaleks comment and since similar pr is merged there's a need in a rebase

**Comment by itorK** [comment]
Sorry for my late answer, but yes @nickaleks  you're right  BOOST_ROOT is enough.

**Comment by l4l** [comment]
Could you update your branch, since PR mentioned earlier was already merged. Thanks

**Comment by neewy** [comment]
Since this PR is stale I would like to close it until the correction mentioned by @l4l is introduced @itorK

**Pull request closed without merging**
