### PR TITLE
Feature/ir 216/transaction processor map

### PR DESCRIPTION
**Pull request by muratovv**
## What is this pull request?
This pr provide effective, but strict realization of transaction processor.
  
## How to use the features provided in the pull request?
There are available:
-  Async api for responses based on rxcpp
-  Stateless validation statuses
-  Tests for current functionality

Limitations:
-  Blocking execution of transaction_notifier
-  Not supported transaction responses for commit, rejects and others
-  Missed testable subscription in tests

## Details/Features
Restore previous interface of transaction processor, thus, restore responsibility of transaction processor for manage transaction statuses.

## Additional dependencies (optional)
In this pr was used gmock. So, after merging this pr into develop all developers may use mocks for own purposes.

### CODE REVIEW

**Comment by muratovv** [comment]
What about reasoning?

**Comment by satellitex** [comment]
We have decided the design drawing.
There is no Transaction Processor there.

**Comment by takemiyamakoto** [comment]
It looks like there's a tx processor to me.

image

**Comment by neewy** [comment]
we definitely need to draw something meaningful as components diagram, this is my fault. Please remind about this in sprint review when we will discuss issues and in case I may forget to say about it

**Comment by takemiyamakoto** [comment]
Transaction Processor proposed to be renamed to TransactionHandler I think.

**Pull request merged**
