### PR TITLE
[chore]: Refer to MAINTAINERS.md in `main` from `iroha1-main`

### PR DESCRIPTION
**Pull request by nxsaken**
## Description

To avoid maintaining two separate MAINTAINERS lists (with the same content), only refer to it from the `iroha1-main` branch.

### Benefits

No need to keep two files in sync.

### Checklist

- [x] I've read `CONTRIBUTING.md`
- [x] I've used the standard signed-off commit format (or will squash just before merging)
- [x] All applicable CI checks pass (or I promised to make them pass later)
- [ ] (optional) I've written unit tests for the code changes
- [ ] I replied to all comments after code review, marking all implemented changes with thumbs up

### CODE REVIEW

**Review by mversic — APPROVED** [review]

**Comment by mversic** [comment]
cool

**Comment by ryjones** [comment]
@nxsaken do you want me to force-merge this?

**Comment by nxsaken** [comment]
@ryjones I wanted you to take a look since this file affects processes, and maybe there is a good reason this file has been maintained on two branches separately that I'm unaware of.

**Comment by ryjones** [comment]
@nxsaken no good reason

**Pull request merged**
