### PR TITLE
removed the Python module

### PR DESCRIPTION
**Pull request by MBoldyrev**
### Description of the Change

It seems no longer needed as the irohapy trget is removed.

### Benefits

A piece of code that is unneeded and won't compile anyway is removed.

### Possible Drawbacks 

Maybe I missed something and it is required somewhere.

### CODE REVIEW

**Comment by igor-egorov** [comment]
We should somehow remove the existing library from pypi when trunk will be merged

**Comment by igor-egorov** [comment]
summon @Stayer

**Comment by igor-egorov** [comment]
summon @bakhtin

**Comment by bakhtin** [comment]
You cannot remove a package from PyPi once it was uploaded there. It can only be replaced with a newer version.

**Comment by l4l** [comment]
I guess it might be either renamed, or have a comment about its obsolescence

**Pull request merged**
