### PR TITLE
 [refactor] #2123: use Algorithm for storing digest function

### PR DESCRIPTION
**Pull request by Retssaze**
Signed-off-by: Retssaze <Retssaze@GMail.Com>

### CODE REVIEW

**Comment by Retssaze** [comment]
Let's see what it is (who it is)

**Comment by Retssaze** [comment]
Previous monster https://github.com/hyperledger/iroha/pull/3055

**Comment by Retssaze** [comment]
What the workflows say now about this Deer

**Comment by Retssaze** [comment]
Should be much better now. Deer is basking in the Sun

**Comment by appetrosyan** [comment]
> Should be much better now.

It is, thank you. 

We have opened the release window for RC.13. 

This PR is a little too late to be included in RC13, so it'll be merged soon after. Estimated time, Wednesday next week.

**Comment by Retssaze** [comment]
Sure

**Comment by Retssaze** [comment]
What if I'll look at   #3141? When it is planned to go?

**Comment by appetrosyan** [comment]
Hi, there's no need to manually update the branch. We'll do that for you.

**Comment by Retssaze** [comment]
No problem

**Comment by Retssaze** [comment]
Guys, are we going to merge this somewhen?

**Comment by appetrosyan** [comment]
> Guys, are we going to merge this somewhen?

As I mentioned, this will be merged in the next release window. This is an API-breaking change, and I'd rather we've had fewer of them for RC13. 

We shall handle it from here. You can consider it merged, given that it has two approvals.

**Comment by Retssaze** [comment]
Dear Alex,

please advise what task to solve

**Comment by appetrosyan** [comment]
#2547 Might be a nice and tidy issue to look into.

**Comment by Retssaze** [comment]
Sure

**Comment by appetrosyan** [comment]
The release PR is merged. Yours is up next.

**Comment by appetrosyan** [comment]
Congrats!

**Comment by Retssaze** [comment]
I am very glad of such news Thank you to everyone!

**Pull request merged**
