### PR TITLE
[refactor]: Rename ISI from *Box to *Expr

### PR DESCRIPTION
**Pull request by mversic**
## Description

1. This was a complete misnomer because `Box` suffix if for enums used to group objects for serialization purpose
2. This is an interlude into another PR where I will introduce proper `Box`ed instructions which will not contain expressions inside them, i.e. they will be evaluated instructions
3. I'm only doing this rename in separate PR first so that changes are not overwhelming to review

### Linked issue

Closes #{issue_number} 

### Checklist

- [ ] I've read `CONTRIBUTING.md`
- [ ] I've used the standard signed-off commit format (or will squash just before merging)
- [ ] All applicable CI checks pass (or I promised to make them pass later)
- [ ] (optional) I've written unit tests for the code changes
- [ ] I replied to all comments after code review, marking all implemented changes with thumbs up

### CODE REVIEW

**Comment by Arjentix** [comment]
> This is an interlude into another PR where I will introduce proper Boxed instructions which will not contain expressions inside them, i.e. they will be evaluated instructions

So do you mean that non existing instructions will be unrepresentable?

**Comment by mversic** [comment]
> So do you mean that non existing instructions will be unrepresentable?

what do you mean by a non existing instruction?

**Review by Arjentix — APPROVED** [review]
I think clicking `Viewed` was harder than searh-n-replace done in this PR 😄

**Comment by Arjentix** [comment]
> what do you mean by a non existing instruction?

Like `Register<u32>` or something like that. I think we have an issue for that: https://github.com/hyperledger/iroha/issues/3612

**Comment by mversic** [comment]
> Like `Register<u32>` or something like that. I think we have an issue for that: #3612

oh, I get what you mean. The answer is kinda yes. Atm, we evaluate expressions twice redundantly, once in executor and then again on the host side. The idea is to move Expression evaluation into executor (and only Executor). What will be representable in the Expression model implemented in Executor is the responsibility of a particular expression implementation. Iroha will offer a RISC API that expression can evaluate into. In that sense expression system will be extandable by writing a custom executor

**Review by Erigara — APPROVED** [review]

**Review by Arjentix — APPROVED** [review]

**Pull request merged**
