### PR TITLE
Feature/hash from hex

### PR DESCRIPTION
**Pull request by Alexey-N-Chernyshov**
### Description of the Change
Add Hash constructor from Blob to be able to create Hash from hex string in Java bindings.

### Benefits
Can create Hash from hex string in Java bindings. It is used for query getTransactions().

### Possible Drawbacks 
no

### CODE REVIEW

**Comment by l4l** [comment]
What's the problem with: `Hash(blob.hex())`?

**Comment by Alexey-N-Chernyshov** [comment]
@l4l, 'blob.hex()' returns hex representation while `Hash(string)` constructor requires binary string. There was no way to create `Hash` from hex string in java bindings.

**Comment by l4l** [comment]
Ah, I see. What about `toBinaryString`:
https://github.com/hyperledger/iroha/blob/f138d79a3fc17b329b61bc31a7463649d11b6978/shared_model/cryptography/blob.hpp#L32

Works in python for me:
screenshot_20180615_145430

**Comment by Alexey-N-Chernyshov** [comment]
It doesn't work in Java. I think it is because of encoding. Moreover the binary string shouldn't appear in client sources.

**Pull request closed without merging**
