### PR TITLE
Support/1.1.x Added instructions how to build iroha on raspberry pi 3 and 4

### PR DESCRIPTION
**Pull request by baziorek**
### Description of the Change
According to talk on community meeting on 6th November I've added new file with instructions how to build iroha on raspberry pi. I've also changed one of file (building.rst) to include my file. Because it necessairy to wrap g++ command to build iroha I've added short program to wrap that command.

### Benefits
Many people on chat are asking about how to build iroha on RPI. I've managed to and described on wiki (https://wiki.hyperledger.org/pages/viewpage.action?pageId=41584046), then Sara suggested to add instructions to documentation instead of wiki.

### Possible Drawbacks 
None (only documentation changes, no impact to source code)

### Usage Examples or Tests *[optional]*
This is documentation so no tests (only manual).

### Alternate Designs *[optional]*
Alternative was Wiki, but Sara asked me to add that kind of description to documentation.

### CODE REVIEW

**Comment by LiraLemur** [comment]
@baziorek thank you so much! 

I've made some small fixes - overall it's great and I think it is possible to push it if @lebdron is OK on the technical side.

**Comment by baziorek** [comment]
> @baziorek thank you so much!
> 
> I've made some small fixes - overall it's great and I think it is possible to push it if @lebdron is OK on the technical side.

Thanks for typo corrections - it really looks better now. I got used to have spell check and I sometimes don't see typos. Also thanks for english corrections.

**Review by lebdron — COMMENTED** [review]
I would suggest to make several patches to vcpkg with the given commit, format them and put in `vcpkg/patches` directory, so that the whole process is automated, and does not need to be followed in the guide. It would be a good idea to look at the master branch of vcpkg, as there were great changes made in order to support arm64-linux platform.

**Comment by baziorek** [comment]
@lebdron I've finally managed to repair one of problems with iroha build - problem with GRPC (in the wiki it is: https://wiki.hyperledger.org/display/iroha/Common+building+problems+for+various+Iroha+versions and jira: https://jira.hyperledger.org/browse/IR-925) - now it is not necessary to use:
```
sed -i 's_\(^.*long gettid(.*$\)_//\1_g' $(find . -name ev_epollex_linux.cc)
sed -i 's_\(^.*long gettid(.*$\)_//\1_g' $(find . -name log_linux.cc)
```
To repair this I needed to change version of VCPKG into ebe505081b667a9f9a56596057f63ed20be237a5 (GRPC has version: 1.26.0). It is not the same version as in branch `support/1.2.x` (here GRPC is 1.31.1). After changing version I had to change patches, two of them was invalid then I needed to add new one.

Not everything is automated yet, but I'll work on this.

**Comment by baziorek** [comment]
@lebdron I've also created question on stack: https://stackoverflow.com/questions/66454424/how-to-remove-c-compilation-flag-of-ninja-from-cmake-run-by-vcpkg -if there won't be any solution we would have to have wrapper for C++ command.

**Comment by baziorek** [comment]
@lebdron I've added auto-wrapping c++ command in build script. Unfortunately nobody on stack: https://stackoverflow.com/questions/66454424/how-to-remove-c-compilation-flag-of-ninja-from-cmake-run-by-vcpkg didn't know how to do this with patch to VCPKG. **Please take a look to code, then I'll change description**.

**Comment by baziorek** [comment]
@lebdron Created pull request: https://github.com/hyperledger/iroha/pull/864 in which all build process is automated. So now I'll remove code changes from my PR.

**Comment by baziorek** [comment]
@LiraLemur After PR from @lebdron #864  I've removed changes in code made by myself. So only documentation changes are here again. Please take a look if it is OK (hopefully I've not introduced new typos:D).

**Review by lebdron — APPROVED** [review]

**Pull request merged**
