### PR TITLE
Keys in hex

### PR DESCRIPTION
**Pull request by Solonets**
### Description of the Change

keys stored in genesis block are in hex

### Benefits

consistent with key files

### Possible Drawbacks 

--

### CODE REVIEW

**Comment by igor-egorov** [comment]
... and DCO signature is missing for the first two commits

**Comment by neewy** [comment]
@igor-egorov @Solonets before merging this PR we need to check if it can break down existing blockstores. So if you merge it please notify everyone in advance over Telegram/Rocketchat

**Comment by igor-egorov** [comment]
Please notify our community when merged

**Comment by neewy** [comment]
Duplicated in https://github.com/hyperledger/iroha/pull/1916 this pull request

**Pull request closed without merging**
